apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: configmap-extra-resources
parameters:
- name: JUPYTERHUB_NAMESPACE
  value: ""
  required: true
- name: JUPYTERHUB_APPLICATION
  value: ""
  required: true
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${JUPYTERHUB_APPLICATION}-res
    namespace: ${JUPYTERHUB_NAMESPACE}
    labels:
      app: ${JUPYTERHUB_APPLICATION}
  data:
    extra_resources.json: |-
      {
        "kind": "List",
        "apiVersion": "v1",
        "items": [
          {
            "kind": "ServiceAccount",
            "apiVersion": "v1",
            "metadata": {
              "name": "strimzi-cluster-operator"
            }
          },
          {
            "kind": "RoleBinding",
            "apiVersion": "rbac.authorization.k8s.io/v1",
            "metadata": {
              "name": "strimzi-cluster-operator"
            },
            "subjects": [
              {
                "kind": "ServiceAccount",
                "name": "strimzi-cluster-operator",
                "namespace": "${project_namespace}"
              }
            ],
            "roleRef": {
              "kind": "ClusterRole",
              "apiGroup": "rbac.authorization.k8s.io",
              "name": "strimzi-cluster-operator-namespaced"
            }
          },
          {
            "kind": "RoleBinding",
            "apiVersion": "rbac.authorization.k8s.io/v1",
            "metadata": {
              "name": "strimzi-cluster-operator-entity-operator-delegation"
            },
            "subjects": [
              {
                "kind": "ServiceAccount",
                "name": "strimzi-cluster-operator",
                "namespace": "${project_namespace}"
              }
            ],
            "roleRef": {
              "kind": "ClusterRole",
              "apiGroup": "rbac.authorization.k8s.io",
              "name": "strimzi-entity-operator"
            }
          },
          {
            "kind": "RoleBinding",
            "apiVersion": "rbac.authorization.k8s.io/v1",
            "metadata": {
              "name": "strimzi-cluster-operator-topic-operator-delegation"
            },
            "subjects": [
              {
                "kind": "ServiceAccount",
                "name": "strimzi-cluster-operator",
                "namespace": "${project_namespace}"
              }
            ],
            "roleRef": {
              "kind": "ClusterRole",
              "apiGroup": "rbac.authorization.k8s.io",
              "name": "strimzi-topic-operator"
            }
          },
          {
            "apiVersion": "extensions/v1beta1",
            "kind": "Deployment",
            "metadata": {
              "name": "strimzi-cluster-operator",
              "labels": {
                "app": "strimzi"
              }
            },
            "spec": {
              "replicas": 1,
              "template": {
                "metadata": {
                  "labels": {
                    "name": "strimzi-cluster-operator",
                    "strimzi.io/kind": "cluster-operator"
                  }
                },
                "spec": {
                  "serviceAccountName": "strimzi-cluster-operator",
                  "containers": [
                    {
                      "name": "strimzi-cluster-operator",
                      "image": "strimzi/cluster-operator:0.11.1",
                      "imagePullPolicy": "IfNotPresent",
                      "env": [
                        {
                          "name": "STRIMZI_NAMESPACE",
                          "valueFrom": {
                            "fieldRef": {
                              "fieldPath": "metadata.namespace"
                            }
                          }
                        },
                        {
                          "name": "STRIMZI_FULL_RECONCILIATION_INTERVAL_MS",
                          "value": "120000"
                        },
                        {
                          "name": "STRIMZI_OPERATION_TIMEOUT_MS",
                          "value": "300000"
                        },
                        {
                          "name": "STRIMZI_DEFAULT_ZOOKEEPER_IMAGE",
                          "value": "strimzi/zookeeper:0.11.1-kafka-2.0.0"
                        },
                        {
                          "name": "STRIMZI_KAFKA_IMAGES",
                          "value": "2.0.0=strimzi/kafka:0.11.1-kafka-2.0.0\n2.0.1=strimzi/kafka:0.11.1-kafka-2.0.1\n2.1.0=strimzi/kafka:0.11.1-kafka-2.1.0\n"
                        },
                        {
                          "name": "STRIMZI_KAFKA_CONNECT_IMAGES",
                          "value": "2.0.0=strimzi/kafka-connect:0.11.1-kafka-2.0.0\n2.0.1=strimzi/kafka-connect:0.11.1-kafka-2.0.1\n2.1.0=strimzi/kafka-connect:0.11.1-kafka-2.1.0\n"
                        },
                        {
                          "name": "STRIMZI_KAFKA_CONNECT_S2I_IMAGES",
                          "value": "2.0.0=strimzi/kafka-connect-s2i:0.11.1-kafka-2.0.0\n2.0.1=strimzi/kafka-connect-s2i:0.11.1-kafka-2.0.1\n2.1.0=strimzi/kafka-connect-s2i:0.11.1-kafka-2.1.0\n"
                        },
                        {
                          "name": "STRIMZI_KAFKA_MIRROR_MAKER_IMAGES",
                          "value": "2.0.0=strimzi/kafka-mirror-maker:0.11.1-kafka-2.0.0\n2.0.1=strimzi/kafka-mirror-maker:0.11.1-kafka-2.0.1\n2.1.0=strimzi/kafka-mirror-maker:0.11.1-kafka-2.1.0\n"
                        },
                        {
                          "name": "STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE",
                          "value": "strimzi/topic-operator:0.11.1"
                        },
                        {
                          "name": "STRIMZI_DEFAULT_USER_OPERATOR_IMAGE",
                          "value": "strimzi/user-operator:0.11.1"
                        },
                        {
                          "name": "STRIMZI_DEFAULT_KAFKA_INIT_IMAGE",
                          "value": "strimzi/kafka-init:0.11.1"
                        },
                        {
                          "name": "STRIMZI_DEFAULT_TLS_SIDECAR_ZOOKEEPER_IMAGE",
                          "value": "strimzi/zookeeper-stunnel:0.11.1"
                        },
                        {
                          "name": "STRIMZI_DEFAULT_TLS_SIDECAR_KAFKA_IMAGE",
                          "value": "strimzi/kafka-stunnel:0.11.1"
                        },
                        {
                          "name": "STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE",
                          "value": "strimzi/entity-operator-stunnel:0.11.1"
                        },
                        {
                          "name": "STRIMZI_LOG_LEVEL",
                          "value": "INFO"
                        }
                      ],
                      "livenessProbe": {
                        "httpGet": {
                          "path": "/healthy",
                          "port": 8080
                        },
                        "initialDelaySeconds": 10,
                        "periodSeconds": 30
                      },
                      "readinessProbe": {
                        "httpGet": {
                          "path": "/ready",
                          "port": 8080
                        },
                        "initialDelaySeconds": 10,
                        "periodSeconds": 30
                      },
                      "resources": {
                        "limits": {
                          "cpu": "1000m",
                          "memory": "256Mi"
                        },
                        "requests": {
                          "cpu": "200m",
                          "memory": "256Mi"
                        }
                      }
                    }
                  ]
                }
              },
              "strategy": {
                "type": "Recreate"
              }
            }
          }
        ]
      }
